### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=8; index=8

### ISSUE THREAD

**Issue by m-o** [sannies/mp4parser#101]
Hi, I am having strange problem. I am recording vidoe files from Android surface(originally from GoPro3) and I am adding audio track.
I get exception on some files. I can play those files, ffprobe does not show anything strange. And the error shows only in combination with audio track.

Example:
Load mp4 - load video8, extract video track, add to new Movie, save - ok;
Load mp4 - load video9, extract video track, add to new Movie, save - ok;
Load mp4 - load video8. extract video, add to new Movie, load .aac file, add to movie, ok;
Load mp4 - load video9. extract video, add to new Movie, load .aac file, add to movie, error;

Files are here: https://www.dropbox.com/sh/jvrd5qovoz488du/AACbFSWHNCxqVO1CE1dTwGIca?dl=0

Here is my code:
```
public void openFiles(){
        String dir = Environment.getExternalStorageDirectory()+"/";
        try {
            String video = dir + "video_track9.mp4";
            Movie originalVideo = MovieCreator.build(video);
            List<Track> tracks = originalVideo.getTracks();
            Track videoTrack = null;
            for (int i = 0; i < tracks.size(); i++) {
                Track t = tracks.get(i);
                if (t.getHandler().equals("vide")){
                    videoTrack = tracks.get(i);
                }
            }
            if(null != videoTrack) {
                Log.d("Main", "start saving: ");
                Uri uri = Uri.parse(dir + "/twentysec.aac");
                AACTrackImpl aacTrack = new AACTrackImpl(new FileDataSourceImpl(uri.getPath()));
                Movie movie = new Movie();
                movie.addTrack(aacTrack);
                movie.addTrack(videoTrack);
                Container mp4file = new DefaultMp4Builder().build(movie);
                FileChannel fc = new FileOutputStream(dir + "test_output_track9.mp4").getChannel();
                mp4file.writeContainer(fc);
                fc.close();
                Log.d("Main", "saving done: " + video);
            }
            else{
                Log.d("Main", "mo video track");
            }
        } catch (IOException e) {
            e.printStackTrace();
            Log.d("Muxing",e.toString());
        }
    }
```

And here is full exception:

    java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:497)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:360)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:321)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:225)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:115)
            at com.example.marek.audiorecorder.MainActivity.openFiles(MainActivity.java:92)
            at com.example.marek.audiorecorder.MainActivity.onClick(MainActivity.java:68)
            at android.view.View.performClick(View.java:4761)
            at android.view.View$PerformClick.run(View.java:19767)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

The problem is, I do not know where to look for the error. Is it in video or audio track?
Also, when I tried to use FragmentedMp4Builder - the movie was saved. But library I use for reading the final file had problems reading it, so FragmentedMp4Builder is not a solution for me...
The error log shows error on line:

```
Container mp4file = new DefaultMp4Builder().build(movie);
```

Thanks for repsonse!

**Comment by m-o** [comment]
Edit: I tried to use diferent audio file, and the problems are the same: vide8 ok, video9 error.

**Comment by sannies** [comment]
Are you using one of the latest builds? 
When I do:

    public static void main(String[] args) {
        String baseDir = "c:\\users\\sannies\\Downloads\\";
        Movie vt8 = MovieCreator.build(baseDir + "video_track8.mp4");
        Movie vt9 = MovieCreator.build(baseDir + "video_track9.mp4");
        Track audio = new AACTrackImpl(new FileDataSourceImpl(baseDir + "twentysec.aac"));
        vt8.addTrack(audio);
        vt9.addTrack(audio);
        Mp4Builder builder = new DefaultMp4Builder();
        Container c = builder.build(vt8);
        c.writeContainer(new FileOutputStream("vt8.mp4").getChannel());
        c = builder.build(vt9);
        c.writeContainer(new FileOutputStream("vt9.mp4").getChannel());
    }


in the master branch both videos just work fine (Do I assume correctly that the audio is silence?)

Would you please try version 1.1.2 from https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1071/ 

That should help!

**Comment by m-o** [comment]
I had version 1.0.6. When I added 1.1.2 I am getting error on both files:

java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:477)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:362)

On line:

Container container = mp4file.build(originalVideo);

**Comment by sannies** [comment]
Ohhh my ... 
I accidentally used List.sort(Comparator) which is only available in Java 8 and therefore not on Android and earlier version of the JSDK. I'm replacing it with Collections.sort(List, Comparator) and build a new build. Gimme 10 minutes

**Comment by sannies** [comment]
1.1.3 and 
https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1072

**Comment by m-o** [comment]
Hi, I updated the library and cleaned the project, but when I try to combine files I get similar error:
```
 Process: com.example.marek.audiorecorder, PID: 19590
    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder$InterleaveChunkMdat.<init>(DefaultMp4Builder.java:650)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder$InterleaveChunkMdat.<init>(DefaultMp4Builder.java:646)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:127)
```

**Comment by sannies** [comment]
Oh my, there was a second one. Could you please grab the master branch and
build it on your own. I removed this second List.sort that caused you to
trip but there might be more. I don't have the time to build a new release
right now or do a thorough review.

Thank you!

Marek Ovečka <notifications@github.com> schrieb am Di., 18. Aug. 2015 um
20:49 Uhr:

**Comment by m-o** [comment]
Ok, thank you. I will try to build it.

**Comment by m-o** [comment]
Hi, I made build but it gives me error on all files:

E/AndroidRuntime﹕ FATAL EXCEPTION: Timer-0
    Process: easycoremedia.vucaster, PID: 18007
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
            at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:57)
            at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
            at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:61)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
            at easycoremedia.vucaster.BufferingMuxer.createFinalMix(BufferingMuxer.java:145)
            at easycoremedia.vucaster.BufferingMuxer.access$400(BufferingMuxer.java:33)
            at easycoremedia.vucaster.BufferingMuxer$StopRecording.run(BufferingMuxer.java:84)
            at java.util.Timer$TimerImpl.run(Timer.java:284)

I do not know, if I made some mistake when building the .jar.
I will be off the internet for few days, so I will be back to this issue after weekend.

**Comment by m-o** [comment]
Hi, I am still getting this error. I dot know, what I am doing wrong. Could you please create build off current version? Thank you!

**Comment by sannies** [comment]
Please find 1.1.4 here:

https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1073

2015-08-25 15:09 GMT+02:00 Marek Ovečka <notifications@github.com>:

**Comment by m-o** [comment]
Works great, thank you!
