### ISSUE TITLE
Common sync samples dont work correctly on huge files?

### ISSUE THREAD

**Issue by Enoray** [sannies/mp4parser#112]
I tried to convert a 2.2gb (7 min video) with [dash.encrypt](https://github.com/castlabs/dashencrypt). I used following resolutions (width) and bitrates:
- 320px 200k
- 480px 400k
- 640px 750k
- 720px 1000k
- 1024px 2000k
- 1600px 3000k
- 1920px 4000k

It works well up to the 1920p (width) resolution where I get a warning, where it tells me there are just 2 Common sync samples, the first and the last of the given sync samples.

```
com.castlabs.dash dash.fragmencrypter 1.2.5
video_OUT-0200.mp4[1]'s starttime after edits: 0.0
video_OUT-2000.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-1000.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-2500.mp4[1]'s starttime after edits: 0.0
video_OUT-0400.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-2500.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-4000.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-0400.mp4[1]'s starttime after edits: 0.0
video_OUT-3000.mp4[1]'s starttime after edits: 0.0
video_OUT-0750.mp4[1]'s starttime after edits: 0.0
video_OUT-1000.mp4[1]'s starttime after edits: 0.0
video_OUT-4000.mp4[1]'s starttime after edits: 0.0
video_OUT-0750.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-2000.mp4[1]'s starttime after edits: 0.0
video_OUT-0200.mp4[2]'s starttime after edits: -0.021333333333333333
video_OUT-3000.mp4[2]'s starttime after edits: -0.021333333333333333
WARNING:     3 - Common:  [         1,      7397,     12524,] [Fri Oct 02 10:15:44 CEST 2015]
WARNING:    63 - In    :  [         1,       251,       501,       751,      1001,      1251,      1501,      1751,      2001,      2251,      2501,      2751,      3001,      3251,      3501,      3751,      4001,      4251,      4501,      4751,      5001,      5251,      5501,      5751,      6001,      6251,      6501,      6751,      7001,      7251,      7397,      7607,      7787,      7955,      8021,      8174,      8423,      8630,      8861,      9073,      9191,      9299,      9549,      9586,      9684,      9744,      9888,     10014,     10197,     10254,     10380,     10449,     10476,     10509,     10539,     10789,     11039,     11289,     11539,     11789,     12039,     12289,     12524,] [Fri Oct 02 10:15:44 CEST 2015]
WARNING: There are less than 25% of common sync samples in the given track. [Fri Oct 02 10:15:44 CEST 2015]
Exception in thread "main" java.lang.RuntimeException: There are less than 25% of common sync samples in the given track.
        at com.googlecode.mp4parser.authoring.builder.SyncSampleIntersectFinderImpl.getCommonIndices(SyncSampleIntersectFinderImpl.java:230)
        at com.googlecode.mp4parser.authoring.builder.SyncSampleIntersectFinderImpl.sampleNumbers(SyncSampleIntersectFinderImpl.java:88)
        at com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence.findFragmentStartSamples(DashFileSetSequence.java:511)
        at com.castlabs.dash.dashfragmenter.sequences.DashFileSetSequence.run(DashFileSetSequence.java:185)
        at com.castlabs.dash.dashfragmenter.cmdlines.DashFileSet.run(DashFileSet.java:44)
        at com.castlabs.dash.dashfragmenter.Main.main(Main.java:48)
```

My convertionscript uses the commands

`$ffmpeg_path -i $input -r 30 -n -vcodec libx264 -strict experimental -threads 12 -vf scale=320-1920:-2 -b:v 200-4000k $output`
and
`$java_path -jar $dash_path dash -x $videofiles`

Everything works fine with smaller sized videos. If I dont use the 1920p it works fine too.

The input video informations:
```
[root@dev-dash ~]# ffprobe input_video.mp4
ffprobe version N-75186-g81071ee Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-9)
  configuration: --enable-libvpx --enable-libvorbis --enable-gpl --enable-libx264
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  1.100 / 57.  1.100
  libavformat    57.  0.100 / 57.  0.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  1.100 /  6.  1.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input_video.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2015-09-30 11:16:32
  Duration: 00:07:00.71, start: 0.000000, bitrate: 42133 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 41810 kb/s, 60 fps, 60 tbr, 60k tbn, 120 tbc (default)
    Metadata:
      creation_time   : 2015-09-30 11:16:32
      handler_name    : Alias Data Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
    Metadata:
      creation_time   : 2015-09-30 11:16:32
      handler_name    : Alias Data Handler

```

The virtual mashine CPU

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 1
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 3
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 4
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 5
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 6
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 7
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 8
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 8
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 8
initial apicid  : 8
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 9
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 9
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 9
initial apicid  : 9
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 10
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 10
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 10
initial apicid  : 10
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 11
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2933.436
cache size      : 4096 KB
physical id     : 11
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 11
initial apicid  : 11
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca 
cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl pni cx16 hypervisor lahf_lm
bogomips        : 5866.87
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

The virtual mashine RAM
```
MemTotal:       16267868 kB
MemFree:        12692572 kB
MemAvailable:   15292384 kB
Buffers:           76628 kB
Cached:          2674104 kB
SwapCached:            0 kB
Active:          3012636 kB
Inactive:         328828 kB
Active(anon):     591244 kB
Inactive(anon):     8420 kB
Active(file):    2421392 kB
Inactive(file):   320408 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:      16506876 kB
SwapFree:       16506876 kB
Dirty:              4140 kB
Writeback:             0 kB
AnonPages:        593096 kB
Mapped:            40384 kB
Shmem:              8616 kB
Slab:              92948 kB
SReclaimable:      53908 kB
SUnreclaim:        39040 kB
KernelStack:        4240 kB
PageTables:        12764 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24640808 kB
Committed_AS:    1260680 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       36916 kB
VmallocChunk:   34359699255 kB
HardwareCorrupted:     0 kB
AnonHugePages:    405504 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       65520 kB
DirectMap2M:    16711680 kB
```

**Comment by sannies** [comment]
Hi,
it looks to me that your encoding simply doesn't have the sync samples
(IDR-frames) at the same sample index for each quality. This is a
precondition to be able to switch between the qualities.
You might want to run
https://github.com/sannies/mp4parser/blob/master/examples/src/main/java/com/googlecode/mp4parser/syncsamples/ListSyncSamples.java
to list all sync samples. You can run ListSyncSamples file1.mp4 file2.mp4
file3.mp4 and the output will be something like:
|Tears_Of_Steel_600000.mp4|Tears_Of_Steel_800000.mp4|Tears_Of_Steel_1000000.mp4|
|         1|         1|         1|
|       251|       251|       251|
|       501|       501|       501|
|       751|       751|       751|
|      1001|      1001|      1001|
|      1251|      1251|      1251|
|      1501|      1501|      1501|
This allows a simple inspection. If the numbers in each row are the same
then there is a problem in the dash.encrypt tool. If the numbers do not
align then there is a problem with your encoding. I made good experience
with 2-pass encodings: The first pass determines the frame type for each
frame and the second pass then uses that information. Therefore it is
impossible that the different qualities do not align.

Best Regards,
Sebastian


---------------------------
I'm available for freelance work



2015-10-02 10:19 GMT+02:00 Enoray <notifications@github.com>:

**Comment by Enoray** [comment]
Thank you for the fast respond!

I'll try to implement the 2-pass enconding in my script and keep you up to date on my experiences with it.

Greetings,
Enoray
