### ISSUE TITLE
FATAL EXEPTION when compiled release apk with Proguard activated

### ISSUE THREAD

**Issue by loikfb** [sannies/mp4parser#143]
11-25 14:43:39.604 7182-7534/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                 Process:, PID: 7182
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.coremedia.iso.boxes.FileTypeBox
                                                     at com.a.a.h.a(Unknown Source)
                                                     at com.a.a.a.a(Unknown Source)
                                                     at com.c.a.d.e(Unknown Source)
                                                     at com.c.a.d.hasNext(Unknown Source)
                                                     at com.c.a.c.h.hasNext(Unknown Source)
                                                     at com.a.a.e.a(Unknown Source)
                                                     at com.c.a.a.b.a.a.a(Unknown Source)
                                                     at com.b.a.a.j.a(Unknown Source)
                                                     at com.b.a.a.j.a(Unknown Source)
                                                     at com.b.a.a.f.a(Unknown Source)
                                                     at com.b.a.a.f.doInBackground(Unknown Source)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
                                                  Caused by: java.lang.ClassNotFoundException: com.coremedia.iso.boxes.FileTypeBox
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:309)
                                                     at java.lang.Class.forName(Class.java:273)
                                                     at com.a.a.h.a(Unknown Source) 
                                                     at com.a.a.a.a(Unknown Source) 
                                                     at com.c.a.d.e(Unknown Source) 
                                                     at com.c.a.d.hasNext(Unknown Source) 
                                                     at com.c.a.c.h.hasNext(Unknown Source) 
                                                     at com.a.a.e.a(Unknown Source) 
                                                     at com.c.a.a.b.a.a.a(Unknown Source) 
                                                     at com.b.a.a.j.a(Unknown Source) 
                                                     at com.b.a.a.j.a(Unknown Source) 
                                                     at com.b.a.a.f.a(Unknown Source) 
                                                     at com.b.a.a.f.doInBackground(Unknown Source) 
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.coremedia.iso.boxes.FileTypeBox" on path: DexPathList[[zip file "/data/app/com.braindropapp.braindrop-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:309) 
                                                     at java.lang.Class.forName(Class.java:273) 
                                                     at com.a.a.h.a(Unknown Source) 
                                                     at com.a.a.a.a(Unknown Source) 
                                                     at com.c.a.d.e(Unknown Source) 
                                                     at com.c.a.d.hasNext(Unknown Source) 
                                                     at com.c.a.c.h.hasNext(Unknown Source) 
                                                     at com.a.a.e.a(Unknown Source) 
                                                     at com.c.a.a.b.a.a.a(Unknown Source) 
                                                     at com.b.a.a.j.a(Unknown Source) 
                                                     at com.b.a.a.j.a(Unknown Source) 
                                                     at com.b.a.a.f.a(Unknown Source) 
                                                     at com.b.a.a.f.doInBackground(Unknown Source) 
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
                                                 	Suppressed: java.lang.ClassNotFoundException: com.coremedia.iso.boxes.FileTypeBox
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 21 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by loikfb** [comment]
Can I juste put -keep class com.coremedia.iso.boxes.FileTypeBox { *; } in my proguard-rules.pro file ?

**Comment by sannies** [comment]
Most likely.
Best Regards,
Sebastian

I'm currently working on a job - need to find time to catch up with
mp4parser mails  - my answers are therefore a bit brief.



2015-11-25 22:29 GMT+01:00 loikfb <notifications@github.com>:

**Comment by loikfb** [comment]
No pb, 

I fix it with these two lines in the proguard-rules.pro file :+1: 

-keep class com.coremedia.iso.boxes.** { *; }
-keep class com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox { *; }

I do not understand WHY, but it works.

**Comment by stonyz** [comment]
In my case, i added the following to proguard-rules.pro,

# For isoparser
-keep class com.coremedia.iso.boxes.** { *; }
-keep class com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox { *; }
-keep class com.googlecode.mp4parser.boxes.apple.** { *; }
-keep class com.mp4parser.iso14496.part15.** { *; }



Basically, whenever I saw ClassNotFoundException like, 

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "$package.$class" on path: DexPathList[[zip file 
```

I added,
-keep class $package.** { *; }
