### ISSUE TITLE
OutOfMemoryError when try to get size of moov box

### ISSUE THREAD

**Issue by sunshinetpu** [sannies/mp4parser#151]
I got OutOfMemoryError when I run this code:
MovieBox moov = isoFile.getBoxes(MovieBox.class).get(0);
mMoovSize = moov.getSize();

Here is the log: 
 java.lang.OutOfMemoryError: Failed to allocate a 1751411830 byte allocation with 13437012 free bytes and 236MB until OOM
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:67)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.coremedia.iso.boxes.MetaBox.getSize(MetaBox.java:95)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
01-15 11:59:05.475: E/AndroidRuntime(10820): 	at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)

**Comment by sunshinetpu** [comment]
I found out that the method getSize() of MetaBox returns error. Here is my meta box:
00000079 6D657461 00000021 68646C72 00000000 00000000 6D647461 00000000 00000000 00000000 00000000 2B6B6579 73000000 00000000 01000000 1B6D6474 61636F6D 2E616E64 726F6964 2E766572 73696F6E 00000025 696C7374 0000001D 00000001 00000015 64617461 00000001 00000000 362E302E 31

**Comment by yuhjay** [comment]
This is an MOV file, and the meta box is not full box. Mp4Parser will read "hdlr" (68646C72) as the size of the next box and then you get OutOfMemoryError. In MOV, 00000021 is the size of hdlr box, not version and flags of meta box. But in ISO 14496-12, meta box is defined as full box and it has version and flags.

**Comment by danikula** [comment]
Same problem. Easy to reproduce with [this file](https://dl.dropboxusercontent.com/u/15506779/persistent/edufii/issues/mp4parser-151.mp4). I use version 1.1.18. 
@sannies Can you take a look?

**Comment by danikula** [comment]
@sannies any news about this issue ?

**Comment by rickfluck** [comment]
This is experienced by us with Android 6.0 (Marshmallow) when using writeRandomMetadata using either version 1.1.17 or 1.1.18. When running on Android 5.1.1 and below, all works as it is supposed too in version 1.1.17, but not in 1.1.18.
 Thanks,
Rick
```
Throwing OutOfMemoryError "Failed to allocate a 1751411830 byte allocation with 7915024 free bytes and 372MB until OOM"
05-25 12:45:11.828 31020-4909/com.gchd.golfcamhd.in_app E/AndroidRuntime: FATAL EXCEPTION: Thread-32199
 Process: com.gchd.golfcamhd.in_app, PID: 31020
java.lang.OutOfMemoryError: Failed to allocate a 1751411830 byte allocation with 7915024 free bytes and 372MB until OOM at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)

at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110) at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
at com.gchd.golfcamhd.MetaDataInsert.findFreeBox(MetaDataInsert.java:215)
at com.gchd.golfcamhd.MetaDataInsert.writeRandomMetadata(MetaDataInsert.java:132)

at java.lang.Thread.run(Thread.java:818)
```

**Comment by sannies** [comment]
Hi, 
I'm sorry that I didn't have look at it before. I'm currently full time at a customer doing something completely different. So the context switch takes more time than usual. I built a release but didn't yet publish to maven central. Please let me know if it fixes your issue. The staging repository URL is:
https://oss.sonatype.org/content/repositories/comgooglecodemp4parser-1090 
will release to central once any of you confirms that it is working.

**Comment by rickfluck** [comment]
Sebastian, 
Thank you for your prompt response regarding these issues. Your newest release (isoparser-1.1.20) fixes these issues for me under both Android 5.0 and most importantly Android 6.0. Well done!
Best regards,
Rick

**Comment by sannies** [comment]
Sorry, I was not quick enough to promote the staging repository and it was
delete. Will release it again later today.

Rick Fluck <notifications@github.com> schrieb am Do., 26. Mai 2016 um
16:16 Uhr:

**Comment by abdullahalkis** [comment]
```
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 440786862 byte allocation with 25165824 free bytes and 89MB until OOM, max allowed footprint 468205296, growth limit 536870912
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:71)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:257)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:168)
        at sun.nio.ch.IOUtil.read(IOUtil.java:195)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:194)
        at com.googlecode.mp4parser.FileDataSourceImpl.read(FileDataSourceImpl.java:41)
        at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:112)
        at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
        at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
        at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
        at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
        at com.coremedia.iso.IsoFile.getMovieBox(IsoFile.java:102)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:51)
```

I took this error how can we solve it.
Thanks
