### ISSUE TITLE
NullPointerException on MovieCreator().build even when file is present on the storage

### ISSUE THREAD

**Issue by anirudha-vfx** [sannies/mp4parser#152]
I'm trying to mux an audio from one mp4 file to another mp4. But I'm getting NullPointerException.
The error method is Movie video = new MovieCreator().build(inVideofile);
I checked the paths, and all paths are working. The files required are present on the location.
The error is pointing in the PropertyBoxParserImpl.java:67 .
The line on the java file is  - "is.close();"
 
Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
01-18 14:42:22.236    8993-9022/? W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
01-18 14:42:22.242    8993-9022/? W/System.err﹕ at com.coremedia.iso.PropertyBoxParserImpl.<init>(PropertyBoxParserImpl.java:67)
01-18 14:42:22.242    8993-9022/? W/System.err﹕ at com.coremedia.iso.IsoFile.<init>(IsoFile.java:59)
01-18 14:42:22.242    8993-9022/? W/System.err﹕ at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:49)
01-18 14:42:22.242    8993-9022/? W/System.err﹕ at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)

Here is the code

Movie outmovie = new Movie();
try {
           Movie video = new MovieCreator().build(inVideofile);
            List<Track> nuTracks = new ArrayList<Track>();
            for (Track track : video.getTracks() )
                 {
                    if (track.getHandler().equals("vide")) 
                    {
                        outmovie.addTrack(track);
                    }
                }
            }
            catch (java.lang.NullPointerException e) {
                Log.d(LOGTAGMUX, "Video Creator " +  e.toString() );
                 e.printStackTrace();
                return;
            }
             catch (RuntimeException e) {
                e.printStackTrace();
                return;
            } catch (IOException e) {
                 Log.d(LOGTAGMUX, "Video Creator " +  e.toString() );
                e.printStackTrace();
                return;
            }

            Movie audio;
            try {
            audio = new MovieCreator().build(inAudiofile);
            }
            catch (java.lang.NullPointerException e) {
                Log.d(LOGTAGMUX, "Audio Creator " +  e.toString() );
                 e.printStackTrace();
                return;
            }
             catch (RuntimeException e) {
                e.printStackTrace();
                return;
            } catch (IOException e) {
                 Log.d(LOGTAGMUX, "Audio Creator " +  e.toString() );
                e.printStackTrace();
                return;
            }

            Track audioTrack = audio.getTracks().get(0);
             outmovie.addTrack(audioTrack);  
            Container out = new DefaultMp4Builder().build(outmovie);

            FileOutputStream fos = new FileOutputStream(outVideo);
           BufferedWritableFileByteChannel byteBufferByteChannel = new          BufferedWritableFileByteChannel(fos);
          out.writeContainer(byteBufferByteChannel);
          byteBufferByteChannel.close();
          fos.close();

**Comment by sannies** [comment]
1. Please format your bug report in a way I can read it. 
2. Take some time read the code that's failing. It is not hard to understand. 

    InputStream is = getClass().getResourceAsStream("/isoparser-default.properties");
 
results in "is == null". The reason is pretty clear in my eyes: You copied the source code into your project and you forgot about the resources.  Don't do that. Use a precompiled version.

**Comment by brian512** [comment]
I have almost the same problem with isoparser-1.0.7.1.jar，
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.googlecode.mp4parser.boxes.mp4.objectdescriptors.ESDescriptor.getSize()' on a null object reference
    at com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox.getContentSize(ESDescriptorBox.java:60)
    at com.googlecode.mp4parser.AbstractBox.getSize(AbstractBox.java:203)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.coremedia.iso.boxes.sampleentry.AudioSampleEntry.getSize(AudioSampleEntry.java:330)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.coremedia.iso.boxes.SampleDescriptionBox.getSize(SampleDescriptionBox.java:112)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)
    at com.googlecode.mp4parser.BasicContainer.getContainerSize(BasicContainer.java:70)
    at com.googlecode.mp4parser.AbstractContainerBox.getSize(AbstractContainerBox.java:57)
    at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder$InterleaveChunkMdat.getDataOffset(DefaultMp4Builder.java:665)
    at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:132)
    at com.joyodream.media.video.MediaMuxerHelper.mixVideoMusic(MediaMuxerHelper.java:122)
    at com.joyodream.rokk.ui.record.RecordPresenter$5.run(RecordPresenter.java:286)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by grosalex** [comment]
Hi,
I'm having a similar issu, I'm using isoparser-1.1.21.jar I'm getting  : 
`java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.coremedia.iso.PropertyBoxParserImpl.<init>(PropertyBoxParserImpl.java:67)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.coremedia.iso.IsoFile.<init>(IsoFile.java:59)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:49)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.actvt.showdown.pluggin.Mp4ParserAudioMuxer.mux(Mp4ParserAudioMuxer.java:31)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.actvt.showdown.pluggin.Utils.mergeAudioAndVideo(Utils.java:217)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.actvt.showdown.pluggin.Utils.access$400(Utils.java:44)
12-20 13:47:07.409 9171-10512/? W/System.err:     at com.actvt.showdown.pluggin.Utils$1.run(Utils.java:200)
12-20 13:47:07.410 9171-10512/? W/System.err:     at java.lang.Thread.run(Thread.java:761)`

When I do 
`            video = new MovieCreator().build(videoFile);
`
I think it can't find a isoparser-default.properties file in the jar or somethink like that? 

Any ideas?

**Comment by nabeelucb** [comment]
@grosalex did you solve your problem? I know it is very late but I am also facing the same issues. It will be appreciated if you help.

**Comment by RandomCouch** [comment]
I've managed to fix this by replacing the line in PropertyBoxParserImpl.java to
`InputStream is = UnityPlayer.currentActivity.getApplicationContext().getAssets().open("isoparser-default.properties");`
