### ISSUE TITLE
Error merging videos: "Cannot merge VisualSampleEntry"

### ISSUE THREAD

**Issue by enoquefcd** [sannies/mp4parser#177]
Greetings, i have the following errors merging some videos

i have a loop adding  video tracks to a list:
`List<com.googlecode.mp4parser.authoring.Track> videoTracks = new LinkedList<com.googlecode.mp4parser.authoring.Track>();`

after that, I add those tracks to a final video:

```
 if (!videoTracks.isEmpty()) {
Movie trackMovie = new Movie();
            	trackMovie.addTrack(new AppendTrack((com.googlecode.mp4parser.authoring.Track[]) videoTracks.toArray(new com.googlecode.mp4parser.authoring.Track[videoTracks.size()])));
            }
```

thats when I get the error:

Exception in thread "main" java.io.IOException: Cannot merge VisualSampleEntry[AvcConfigurationBox{avcDecoderConfigurationRecord=AvcDecoderConfigurationRecord{configurationVersion=1, avcProfileIndication=66, profileCompatibility=192, avcLevelIndication=30, lengthSizeMinusOne=3, hasExts=false, chromaFormat=-1, bitDepthLumaMinus8=-1, bitDepthChromaMinus8=-1, lengthSizeMinusOnePaddingBits=63, numberOfSequenceParameterSetsPaddingBits=7, chromaFormatPaddingBits=31, bitDepthLumaMinus8PaddingBits=31, bitDepthChromaMinus8PaddingBits=31}};com.coremedia.iso.boxes.UnknownBox@757fe679] and AudioSampleEntry{bytesPerSample=0, bytesPerFrame=0, bytesPerPacket=0, samplesPerPacket=0, packetSize=0, compressionId=0, soundVersion=0, sampleRate=48000, sampleSize=16, channelCount=1, boxes=[com.googlecode.mp4parser.boxes.mp4.ESDescriptorBox@b91b1dff]}
	at com.googlecode.mp4parser.authoring.tracks.AppendTrack.mergeStsds(AppendTrack.java:116)
	at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(AppendTrack.java:59)
	at noob2Star.Noob2Star.main(Noob2Star.java:110)
```

**Comment by enoquefcd** [comment]
PS: all videos are exaclty equal

**Comment by enoquefcd** [comment]
nevermind my dumbness, was trying to merge all tracks (video with audio)
