### ISSUE TITLE
Error launching sample MetaDataTool

### ISSUE THREAD

**Issue by danikula** [sannies/mp4parser#183]
I try to launch sample `MetaDataTool` for [this video](https://raw.githubusercontent.com/danikula/AndroidVideoCache/master/files/orange1.mp4), but samples crashes:
```
java.lang.RuntimeException: Cannot start at / - only relative path expression into the structure are allowed
	at org.mp4parser.tools.Path.getPaths(Path.java:77)
	at org.mp4parser.tools.Path.getPaths(Path.java:67)
	at org.mp4parser.tools.Path.getPath(Path.java:44)
	at com.googlecode.mp4parser.stuff.MetaDataTool.<init>(MetaDataTool.java:87)
	at com.googlecode.mp4parser.stuff.MetaDataTool.main(MetaDataTool.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
I tried to change line `userDataBox = Path.getPath(isoFile, "/moov/udta");` to `userDataBox = Path.getPath(isoFile, "moov/udta");` but it doesn't help: 
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.googlecode.mp4parser.stuff.MetaDataTool.getBox(MetaDataTool.java:267)
	at com.googlecode.mp4parser.stuff.MetaDataTool.setTitle(MetaDataTool.java:380)
	at com.googlecode.mp4parser.stuff.MetaDataTool.main(MetaDataTool.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by hongtaozuo** [comment]
me too
