### ISSUE TITLE
 java.io.IOException: Expected Start Word 0xfff

### ISSUE THREAD

**Issue by tianqiujie** [sannies/mp4parser#192]
at org.mp4parser.muxer.tracks.AACTrackImpl.readADTSHeader(AACTrackImpl.java:268)
W/System.err:  at org.mp4parser.muxer.tracks.AACTrackImpl.readSamples(AACTrackImpl.java:300)
W/System.err:  at org.mp4parser.muxer.tracks.AACTrackImpl.<init>(AACTrackImpl.java:137)
W/System.err:  at org.mp4parser.muxer.tracks.AACTrackImpl.<init>(AACTrackImpl.java:130)

mycode:
 try {
            Movie m = MovieCreator.build(name);
            List<Track> nuTracks = new ArrayList<Track>();
            for (Track track : m.getTracks()) {
                if (!"soun".equals(track)) {
                    nuTracks.add(track);
                }
            }
            nuTracks.add(new AACTrackImpl(new FileDataSourceImpl(name.replace(".wav", ".aac"))));
            m.setTracks(nuTracks);

            BasicContainer out2 = (BasicContainer) new DefaultMp4Builder().build(m);
            FileChannel fc2 = new RandomAccessFile(name, "rw").getChannel();
            out2.writeContainer(fc2);
            fc2.close();

        }catch (Exception e){
            e.printStackTrace();
        }

**Comment by tianqiujie** [comment]
mp4:Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2016-05-07 11:16:55
  Duration: 00:00:02.00, start: 0.000000, bitrate: 38 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 192x192, 35 kb/s, 1 fps, 1 tbr, 1 tbn, 2 tbc (default)
    Metadata:
      creation_time   : 2016-05-07 11:16:55
      encoder         : JCodec

acc:
Input #0, aac, from '/Users/tian/Desktop/回声_2016_05_07_19_16_51.aac':
  Duration: 00:00:02.32, bitrate: 63 kb/s
    Stream #0:0: Audio: aac (LC), 44100 Hz, mono, fltp, 63 kb/s

**Comment by FanHongchuang** [comment]
Hello,
Are you resolve it?
