### ISSUE TITLE
Android java.lang.IllegalArgumentException: offset=x size=y

### ISSUE THREAD

**Issue by grosalex** [sannies/mp4parser#194]
Hi,
I'm trying to trim video on Android but sometimes on large file when I'm trimming closed to the end I've the following exceptions : 

`java.lang.IllegalArgumentException: offset=3156516864 size=425973
                                                                     at java.nio.MemoryBlock.mmap(MemoryBlock.java:107)
                                                                     at java.nio.FileChannelImpl.map(FileChannelImpl.java:257)
                                                                     at com.googlecode.mp4parser.FileDataSourceImpl.map(FileDataSourceImpl.java:62)
                                                                     at com.googlecode.mp4parser.BasicContainer.getByteBuffer(BasicContainer.java:223)
                                                                     at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.asByteBuffer(DefaultMp4SampleList.java:204)
                                                                     at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.writeTo(DefaultMp4SampleList.java:181)
                                                                     at com.actvt.actvt.MP4Creator$InterleaveChunkMdat.getBox(MP4Creator.java:791)
                                                                     at com.googlecode.mp4parser.BasicContainer.writeContainer(BasicContainer.java:216)
                                                                     at com.actvt.actvt.Footage.trim(Footage.java:435)
                                                                     at com.actvt.actvt.CreateExperienceActivity$12.run(CreateExperienceActivity.java:691)
                                                                     at java.lang.Thread.run(Thread.java:818)`

Regards,

**Comment by grosalex** [comment]
Hi,
I've found a solution to my issu.
Just use : 
`MovieCreator.build(new FileDataSourceViaHeapImpl(path));`

To instantiate movie and goes allright.
