### ISSUE TITLE
A cast to int has gone wrong. Please contact the mp4parser discussion group (2332179761)

### ISSUE THREAD

**Issue by grennis** [sannies/mp4parser#216]
Hi, I got this error trying to combine MP4s that had just been recorded by the MediaRecorder. 

This worked fine on my galaxy S5 (Android 6) and also on nexus 4 (Android 5.1), 

But using phone Motorola X (XT1053) with Android 5.1 I got this exception. Any ideas what might be the issue?

Using latest version 1.1.21.

07-14 15:12:45.112 10854-10894/? W/System.err: java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3878608261)
07-14 15:12:45.120 10854-10867/? W/art: Suspending all threads took: 6.012ms
07-14 15:12:45.125 10854-10894/? W/System.err:     at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
07-14 15:12:45.125 10854-10894/? W/System.err:     at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
07-14 15:12:45.125 10854-10894/? W/System.err:     at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
07-14 15:12:45.125 10854-10894/? W/System.err:     at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
07-14 15:12:45.125 10854-10894/? W/System.err:     at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
07-14 15:12:45.131 10854-10894/? W/System.err:     at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
07-14 15:12:45.132 10854-10894/? W/System.err:     at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)

**Comment by diha-o** [comment]
same

**Comment by mweiczorek** [comment]
This happens when I try to parse a file > 2GB. The "cast to int" is the clue, if the file size is larger than what a signed 32-bit int can hold. Perhaps wherever this happens, should use `long` instead?

**Comment by kishanverma26** [comment]
same issue with me but file size is less the 10 MB

**Comment by AllwinJohnson** [comment]
I have found this issue in two phones Moto g5 plus and Moto z2 play, other devices are fine. The crash occurs in 
`Movie m = MovieCreator.build(video);` 
where `video` is the path to the video file in internal memory.
Error log
![image (7)](https://user-images.githubusercontent.com/46625967/90748983-7c14fc80-e2f0-11ea-9ee3-5468b586106a.png)

**Comment by Christophe-Chantraine-djm-digital** [comment]
Hello, 

I have exactly the same exception sometimes with short videos. 
Do you have any solution to this ?

**Comment by Lapinou42** [comment]
Hello,
I have exactly the same exception sometimes with short videos. 
Do you have any solutions to this ?

**Comment by Lapinou42** [comment]
Well, for someone who have the same error (I'm on Xamarin Android but it's the same on Android):

I use the 1.1.8 version that seems to fix the Cast to int error.
Then, I check if a file exists at the same path used in the MovieCreator.build(path) and if it exists, I delete it.
This resolves the OOM exception.

See => https://github.com/sannies/mp4parser/issues/139#issuecomment-240029219

**Comment by r4lly99** [comment]
Is there a new update for this issue?

**Comment by febinmathew** [comment]
Any updates?
