### ISSUE TITLE
OutOfMemoryError on nexus 6 video

### ISSUE THREAD

**Issue by Artem-dsi** [sannies/mp4parser#239]
Hello.
I added mp4parser 1.9.27 as gradle dependency.

I'm trying to build a movie
`MovieCreator.build(filePath)`

OOM occurs only on videos, which were captured on device.
I debugged method `parse` of AbstractBoxParser. 
size/type:

- 24/ftyp
- 1527/moov
- 108/mhvd
- 121/meta
- 1751411826/��������

This is [video](https://github.com/sannies/mp4parser/files/674414/VID_20160328_142335.mp4.zip). 

Do you have any suggestions? Maybe, I can help with something else?

Thank you.

Stack trace:
java.lang.OutOfMemoryError: Failed to allocate a 1751411837 byte allocation with 16766280 free bytes and 484MB until OOM
                                                            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                            at java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:58)
                                                            at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:240)
                                                            at org.mp4parser.support.AbstractBox.parse(AbstractBox.java:95)
                                                            at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                            at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                            at org.mp4parser.boxes.iso14496.part12.MetaBox.parse(MetaBox.java:82)
                                                            at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                            at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                            at org.mp4parser.support.AbstractContainerBox.parse(AbstractContainerBox.java:75)
                                                            at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                            at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                            at org.mp4parser.IsoFile.<init>(IsoFile.java:55)
                                                            at org.mp4parser.IsoFile.<init>(IsoFile.java:50)
                                                            at org.mp4parser.muxer.container.mp4.MovieCreator.build(MovieCreator.java:54)
                                                            at org.mp4parser.muxer.container.mp4.MovieCreator.build(MovieCreator.java:39)

**Comment by Artem-dsi** [comment]
With help of debugging, if I rewind header before parsing type - it displays that type is 'hdlr'

**Comment by OrangeDynamic** [comment]
Same problem here!

**Comment by whiteLT** [comment]
Same. Version 1.1.7 works

**Comment by Pretorian1** [comment]
Thank you @whiteLT your comment save my time
