### ISSUE TITLE
SubTitleExample ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nguydavi** [sannies/mp4parser#24]
Hi,

I was trying to run the SubTitleExample but I got this:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:477)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:340)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:301)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:213)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:115)
        at com.googlecode.mp4parser.SubTitleExample.main(SubTitleExample.java:42)
```

After running `git bisect` it seems this commit 7e2d5c4 introduced the issue:

```
commit 7e2d5c43cb8714e3f0493e9d50256d0e1f343be7
Author: Sebastian Annies <Sebastian.Annies@castlabs.com>
Date:   Wed Aug 20 20:22:03 2014 +0200

    Made TwoSecondsIntersectionFinder work with samples much longer than two seconds (e.g. subtitles)
```

which added only one line. I'm not sure what does that line do but removing it from current master branch makes SubTitleExample run for me.

Best,

David

**Comment by jmgirven** [comment]
Hi,

I am getting effectively the same exception for the ShortenExample in some cases:

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(SourceFile:477)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(SourceFile:340)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(SourceFile:301)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(SourceFile:213)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(SourceFile:115)
```

The code works for videos I have recorded using an Android MediaRecorder. I am able to edit videos down to a shorter length. However, when I try working with another file, specifically any I have imported from my GoPro 3+, I get the above exception. GoPro recorded files are MP4 H.264 files, so I think they should work with mp4parser.

https://gopro.com/support/articles/programs-to-view-and-edit-videos-on-a-pc

Could you guys host a compiled version somewhere with the above proposed fix, so that I could test it? A lot of the other issues raised here and on SO seem related to compiling the library, so I am trying to avoid it.

Thanks,
Jon.
