### ISSUE TITLE
1.1.22 --- java.lang.ArrayIndexOutOfBoundsException: length=55; index=55

### ISSUE THREAD

**Issue by flztsj** [sannies/mp4parser#260]
06-05 09:56:16.685 6786-7100/com.transsion.magicshow E/AndroidRuntime: FATAL EXCEPTION: pool-18-thread-3
                                                                       Process: com.transsion.magicshow, PID: 6786
                                                                       java.lang.ArrayIndexOutOfBoundsException: length=55; index=55
                                                                           at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:85)
                                                                           at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
                                                                           at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
                                                                           at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
                                                                           at com.transsion.magicmovie.trimmer.utils.TrimVideoUtils.genVideoUsingMp4Parser(TrimVideoUtils.java:80)
                                                                           at com.transsion.magicmovie.trimmer.utils.TrimVideoUtils.startTrim(TrimVideoUtils.java:69)
                                                                           at com.transsion.magicmovie.trimmer.K4LVideoTrimmer$9.execute(K4LVideoTrimmer.java:267)
                                                                           at com.transsion.magicmovie.trimmer.utils.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)

**Comment by zhoupanjie** [comment]
have the same question

**Comment by XinYiWorld** [comment]
I hava the same problem,it happend when I use mp4parser make a new video(no mattar cut or merge),
if I use the new video to merge or cut with any other video,the problem happens.
