### ISSUE TITLE
When select audio file getting MP4Parser.BasicContainer.getBoxes

### ISSUE THREAD

**Issue by Anand530** [sannies/mp4parser#261]
Process: com.wos.capturevideowithaudio, PID: 7162
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.googlecode.mp4parser.BasicContainer.getBoxes(java.lang.Class)' on a null object reference
                                                                             at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:48)
                                                                             at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:35)
                                                                             at com.wos.capturevideowithaudio.activity.AudioMixing.appendTwoVideo(AudioMixing.java:154)
                                                                             at com.wos.capturevideowithaudio.activity.AudioMixing$1.onItemClick(AudioMixing.java:142)
                                                                             at com.wos.capturevideowithaudio.adapter.AudioListAdapter$ViewHolder.onClick(AudioListAdapter.java:60)
                                                                             at android.view.View.performClick(View.java:5612)
                                                                             at android.view.View$PerformClick.run(View.java:22285)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by MachineTribe** [comment]
Is there any resolution to this issue? I am having the exact same issue.

**Comment by Anand530** [comment]
I have solve this issue...

**Comment by linzeqi** [comment]
could you let me know how you solved this issue? Because I have it too
