### ISSUE TITLE
MP4Parser.BasicContainer.getBoxes

### ISSUE THREAD

**Issue by kelebro63** [sannies/mp4parser#283]
I try get Movie
`FileDataSourceImpl file = new FileDataSourceImpl(srcFile);
 Movie movie = MovieCreator.build(file);`

and catch
`10-09 12:24:11.397: W/System.err(316): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.googlecode.mp4parser.BasicContainer.getBoxes(java.lang.Class)' on a null object reference
10-09 12:24:11.398: W/System.err(316): 	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:51)
10-09 12:24:11.398: W/System.err(316): 	at com.my_app.utils.Mp4Shorter.cutVideo(Mp4Shorter.java:44)
10-09 12:24:11.398: W/System.err(316): 	at com.my_app.utils.Mp4Shorter.cutVideo(Mp4Shorter.java:30)
10-09 12:24:11.398: W/System.err(316): 	at com.my_app.media_picker.camera.ImageProcessingPresenter.lambda$processVideo$4(ImageProcessingPresenter.java:48)
10-09 12:24:11.399: W/System.err(316): 	at com.my_app.ui.creation_flow.media_picker.camera.ImageProcessingPresenter$$Lambda$3.call(Unknown Source)
10-09 12:24:11.399: W/System.err(316): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
10-09 12:24:11.399: W/System.err(316): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
10-09 12:24:11.399: W/System.err(316): 	at rx.Observable.unsafeSubscribe(Observable.java:10346)
10-09 12:24:11.399: W/System.err(316): 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
10-09 12:24:11.399: W/System.err(316): 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
10-09 12:24:11.399: W/System.err(316): 	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
10-09 12:24:11.399: W/System.err(316): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-09 12:24:11.399: W/System.err(316): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-09 12:24:11.399: W/System.err(316): 	at java.lang.Thread.run(Thread.java:762)`

**Comment by muqeemht** [comment]
I am also facing this issue with .mkv file.

**Comment by mobilekbs** [comment]
Hell, 

Did anyone resolve this issue? I am also facing this issue and am on a very critical stage of the development. Kindly look into this ASAP! 

Thank you
