### ISSUE TITLE
OutOfMemory error on opening file via IsoFile

### ISSUE THREAD

**Issue by alexeyvasilyev** [sannies/mp4parser#284]
Constantly getting OutOfMemory error on any MP4 file written by Android device when opening file via IsoFile. Tested on MP4 files created by default camera apps Samsung S5 Android 6.0.1 and Nexus 6P Android 8.0.

STEPS TO REPRODUCE

```
new IsoFile("mp4parser_isofile_outofmemory.mp4");
```
File to test https://www.dropbox.com/s/3jdd5dii1in0o5u/mp4parser_isofile_outofmemory.mp4?dl=0

Using org.mp4parser:isoparser:1.9.31 on Android.
ISO Viewer app v2.0.2 also has this issue.

```
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1751411832 byte allocation with 4016136 free bytes and 508MB until OOM, max allowed footprint 8032272, growth limit 536870912
                                                                         at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
                                                                         at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
                                                                         at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
                                                                         at org.mp4parser.support.AbstractBox.parse(AbstractBox.java:96)
                                                                         at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:104)
                                                                         at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                                         at org.mp4parser.boxes.iso14496.part12.MetaBox.parse(MetaBox.java:82)
                                                                         at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:104)
                                                                         at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                                         at org.mp4parser.support.AbstractContainerBox.parse(AbstractContainerBox.java:75)
                                                                         at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:104)
                                                                         at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
                                                                         at org.mp4parser.IsoFile.<init>(IsoFile.java:57)
                                                                         at org.mp4parser.IsoFile.<init>(IsoFile.java:44)
```

**Comment by alexeyvasilyev** [comment]
Looks like this is the same issue https://github.com/sannies/mp4parser/issues/240

**Comment by TinyCam** [comment]
mp4parser is parsing the files according to [ISO14496-12 spec](http://xhelmboyx.tripod.com/formats/mp4-layout.txt). However, the file is formatted according to [Quick Time File Format Specification](https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html). The key difference is that in ISO format, the 'meta' box contains two additional fields that precede the 'hdlr' box, namely,  8-bit version and  24-bit flag values. As the result, the data is shifted by 4 bytes.

The crash happens when the code tries to parse metadata ('meta') box. According to the [ISO14496-12 format](http://xhelmboyx.tripod.com/formats/mp4-layout.txt), the first metadata sub-box is the handler reference box ('hdlr'), which (as all boxes do) should start with 4-bytes representing the length. However, because of the 4-byte shift, the parser points to 'hldr' ASCII bytes (which equal to 1751411826) and interprets them as length. That is the reason why you see: java.lang.OutOfMemoryError: Failed to allocate a 1751411832 byte.

The solution could be to determine the type of the metadata format and parse it accordingly.

**Comment by bbrown-extensis** [comment]
TinyCam, thank you for the analysis. This problem has been frustrating me for a long time. I believe this https://github.com/sannies/mp4parser/issues/139 is the same problem. I wonder how I can tell which format. Perhaps I can get some time to work on this and submit a patch.

**Comment by andreikap** [comment]
It should be possible to reset the ByteBuffer position back 4 bytes in [MetaBox.parseVersionAndFlags()](https://github.com/sannies/mp4parser/blob/95badfe47616717556e0269f9d03efc8ab6ba371/isoparser/src/main/java/org/mp4parser/boxes/iso14496/part12/MetaBox.java#L73) if the next 4 bytes represent 'hdlr' after reading the version and flags. For extra verification, the 9th to 12th bytes after 'hdlr' should contain 'mdta' (see [Metadata Handler Atom](https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW11)].

**Comment by croorc** [comment]
Having the same issue on Android 8.1.0 from a file recorded on device from camera using android.media.MediaRecorder: 

Caused by java.lang.OutOfMemoryError
--
  | java.nio.HeapByteBuffer.<init> (HeapByteBuffer.java:54)
  | java.nio.ByteBuffer.allocate (ByteBuffer.java:261)
  | org.mp4parser.support.AbstractBox.parse (AbstractBox.java:96)
  | org.mp4parser.AbstractBoxParser.parseBox (AbstractBoxParser.java:104)
  | org.mp4parser.BasicContainer.initContainer (BasicContainer.java:107)
  | org.mp4parser.boxes.iso14496.part12.MetaBox.parse (MetaBox.java:82)
  | org.mp4parser.AbstractBoxParser.parseBox (AbstractBoxParser.java:104)
  | org.mp4parser.BasicContainer.initContainer (BasicContainer.java:107)
  | org.mp4parser.support.AbstractContainerBox.parse (AbstractContainerBox.java:75)
  | org.mp4parser.AbstractBoxParser.parseBox (AbstractBoxParser.java:104)
  | org.mp4parser.BasicContainer.initContainer (BasicContainer.java:107)
  | org.mp4parser.IsoFile.<init> (IsoFile.java:57)
  | org.mp4parser.IsoFile.<init> (IsoFile.java:40)

**Comment by YitianTonyXu** [comment]
I just ran in to this issue today. Is there anyway for us to merge in the pull request with the fix?

**Comment by HBiSoft** [comment]
@YitianTonyXu can you please confirm if 1.9.37 - #288 fixed this issue?
