### ISSUE TITLE
Box.getBox is not thread safe

### ISSUE THREAD

**Issue by galbarm** [sannies/mp4parser#289]
calling Box.getBox(WritableByteChannel writableByteChannel) from multiple threads has a race condition that sometimes ends with:

java.lang.IllegalArgumentException
at java.nio.Buffer.position(Buffer.java:244)
at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:209)
at com.googlecode.mp4parser.util.ByteBufferByteChannel.write(ByteBufferByteChannel.java:52)
at com.googlecode.mp4parser.AbstractBox.getBox(AbstractBox.java:136)
at com.googlecode.mp4parser.BasicContainer.writeContainer(BasicContainer.java:216)
at com.googlecode.mp4parser.AbstractContainerBox.getBox(AbstractContainerBox.java:88)
at com.googlecode.mp4parser.BasicContainer.writeContainer(BasicContainer.java:216)
at com.googlecode.mp4parser.AbstractContainerBox.getBox(AbstractContainerBox.java:88)

**Comment by galbarm** [comment]
Seems like it is caused due to modification of the position of
`private ByteBuffer content (in class AbstractBox)`
