### ISSUE TITLE
Getting an RunTimeException with  H264TrackImpl h264Track = new H264TrackImpl(new FileDataSourceImpl(videoPath))

### ISSUE THREAD

**Issue by abdullah-github** [sannies/mp4parser#292]
I am getting this error while running above code:
java.lang.RuntimeException: Sequence parameter set extension is not yet handled. Needs TLC.
                                                                                at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:347)
                                                                                at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:107)
                                                                                at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:83)
                                                                                at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:87)
                                                                                at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:91)
                                                                                at abdullahhafeez.me.prototype2.Services.VideoBuildService.onHandleIntent(VideoBuildService.java:103)

**Comment by lovepreetsinghmansa** [comment]
I am getting the same error! Did you find any solution?
