### ISSUE TITLE
mp4parser gives NullPointerException in DefaultMp4Builder.build

### ISSUE THREAD

**Issue by suitianshi** [sannies/mp4parser#30]
I'm using the latest build 1.0.5.3 jar package. the call stack is as following: video format is mpeg4

at com.googlecode.mp4parser.authoring.tracks.AppendTrack.getSyncSamples(AppendTrack.java:426)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStss(DefaultMp4Builder.java:521)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:336)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:301)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:213)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:115)
            at com.ss.android.newmedia.app.VideoMerger$1.run(VideoMerger.java:80)
            at java.lang.Thread.run(Thread.java:841)

**Comment by sannies** [comment]
Hi, 
Christmas time was a bit hectic and your request was not handled at all. Sorry for that. Due to the fact that you didn't ping me again I assume that your problem is solved or that you moved on. Therefore I'm closing issue. Please re-open if you are still interested or if you have other problems
BR,
Sebastian
