### ISSUE TITLE
MP3TrackImpl

### ISSUE THREAD

**Issue by JamesYang1624** [sannies/mp4parser#302]
I'm having problems mixing MP4 with MP3，err
03-23 18:08:02.328 14798-14798/com.jh.mp4parserdemo W/System.err: java.io.IOException: Expected Start Word 0x7ff
03-23 18:08:02.328 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.readMP3Header(MP3TrackImpl.java:183)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.readSamples(MP3TrackImpl.java:154)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:60)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.googlecode.mp4parser.authoring.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:53)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.jh.mp4parserdemo.MainActivity.muxAacMp4(MainActivity.java:63)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.jh.mp4parserdemo.MainActivity$1.onClick(MainActivity.java:51)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.view.View.performClick(View.java:5646)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.view.View$PerformClick.run(View.java:22473)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.os.Looper.loop(Looper.java:156)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
03-23 18:08:02.329 14798-14798/com.jh.mp4parserdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

How to fix it?

**Comment by jiprolog** [comment]
I have the same problem and looking for a solution

**Comment by huunhan18pro** [comment]
Hi @JamesYang1624 , Did you get a solution to mixing mp4 and mp3?
