### ISSUE TITLE
A cast to int has gone wrong. Please contact the mp4parser discussion group (3758175784)

### ISSUE THREAD

**Issue by Aryanr64x** [sannies/mp4parser#314]
I am getting the arror in 
`
 movies.add(MovieCreator.build(path));
`
The path is write . The full error says
06-29 21:57:04.652 9461-9461/com.example.hp.resonance E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hp.resonance, PID: 9461
    java.lang.RuntimeException: A cast to int has gone wrong. Please contact the mp4parser discussion group (3758175784)
        at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
        at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
        at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
        at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
        at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
        at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
        at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
        at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
        at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
        at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
        at com.example.hp.resonance.app.helpers.AudioRecording.AudioMixer.mixAndSaveAudio(AudioMixer.java:28)
        at com.example.hp.resonance.app.helpers.AudioRecording.AudioRecorder.stopRecording(AudioRecorder.java:124)
        at com.example.hp.resonance.activities.AppRecorderActivity.onClick(AppRecorderActivity.java:90)
        at android.view.View.performClick(View.java:4848)
        at android.view.View$PerformClick.run(View.java:20277)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5643)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ltlovezh** [comment]
do you have the solution？I have meet this problem.
