### ISSUE TITLE
MovieCreator.build(videoUri)  getTracks empty

### ISSUE THREAD

**Issue by shoyu666** [sannies/mp4parser#320]
Movie m = MovieCreator.build(videoUri) 
 m.getTracks()  is empty

use AppendTrack throw
 java.util.NoSuchElementException
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at org.mp4parser.muxer.builder.DefaultMp4Builder.getTimescale(DefaultMp4Builder.java:628)
	at org.mp4parser.muxer.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:179)
	at org.mp4parser.muxer.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:110)
	at com.googlecode.mp4parser.AppendExample.main(AppendExample.java:59)

**Comment by HBiSoft** [comment]
@shoyu666 

I implemented mine like this, hope it helps you.

```
public static MediaInfo extract(String filePath) throws IOException, IllegalArgumentException {
        MediaInfo mediaInfo = new MediaInfo();
        Movie video;

        // using MovieCreator.build(filePath); in a synchronized block - I don't think this is necessary anymore.
        synchronized (MY_OBJECT){
            video = MovieCreator.build(filePath);
        }

        // getting track info in a for loop
        for(int i=0; i<video.getTracks().size();i++){
            // get tracks
            Track videoTrack = video.getTracks().get(i);
            if(videoTrack.getHandler().equals(MP4_VIDEO_TAG)){

                // declaring track meta data
                TrackMetaData metaData = videoTrack.getTrackMetaData();

                // get time scale
                long timeScale = metaData.getTimescale();

                // get video width
                mediaInfo.width = metaData.getWidth();
                // get video height
                mediaInfo.height = metaData.getHeight();

                // get video rotation
                mediaInfo.rotation = convertMatrixToRotation(metaData.getMatrix());

                // get duration in Us
                mediaInfo.durationUs = videoTrack.getDuration() * 1000 *1000 / timeScale;

                // get total frames
                mediaInfo.totalFrames = videoTrack.getSamples().size();

                // calculate the fps
                mediaInfo.perFrameDurationUs =  mediaInfo.durationUs /  mediaInfo.totalFrames;
                mediaInfo.fps = 1*1000*1000 / mediaInfo.perFrameDurationUs;

                // get information of key frames
                mediaInfo.keyFrameIndexes = videoTrack.getSyncSamples().clone();
                return mediaInfo;
            }
        }
        throw new IllegalArgumentException("Cannot find video track in target file.");
    }
```

**Comment by HBiSoft** [comment]
This happens because you are passing a `Uri` instead of the file path. I know on Android 10> we can no longer access the file path where we could previously access the path from the `_data` column using `ContentResolver`. I hope the author will provide an option to pass a `FileInputStream` instead of a file path since there is currently no way to pass a file path unless you copy the file to your applications directory.
