### ISSUE TITLE
need help------------getBoxes(java.lang.Class)' on a null object

### ISSUE THREAD

**Issue by youarenowhere** [sannies/mp4parser#336]
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.coremedia.iso.boxes.MovieBox.getBoxes(java.lang.Class)' on a null object reference
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:51)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)

**Comment by Ozeias01Nunes** [comment]
I have the same problem.

**Comment by sannies** [comment]
You are using the old version, 1st thing you should do is to use the latest
version 1.9.x

But please be aware that this project is orphaned. I'm not maintaining, I'm
not supporting it. (Except paid maintenance or paid support, rate is
100$/h).


Am Do., 25. Apr. 2019 um 10:13 Uhr schrieb Ozeias01Nunes <
notifications@github.com>:

**Comment by Ozeias01Nunes** [comment]
And where do I find version 1.9.x or 2.x.x?

ERROR: Failed to resolve: com.googlecode.mp4parser: isoparser: 1.9.37
ERROR: Failed to resolve: com.googlecode.mp4parser: isoparser: 2.0.0

**Comment by emiliofonseca** [comment]
@Ozeias01Nunes, it is "org.mp4parser:isoparser:1.9.39" now

Here is the link
https://mvnrepository.com/artifact/org.mp4parser/isoparser/1.9.39
