### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by yesusok** [sannies/mp4parser#351]
MoveCreator.build(sourceFile); When invoked, the following problem occurs. 

This happens when you trim an mp4 file recorded with the du recorder app. I do not know the reason.

i used isoparser 1.1.22. - device vivo 1716 (android os 8.1)

2018-12-17 11:20:53.996 14546-15174/? E/UncaughtException: java.lang.OutOfMemoryError: Failed to allocate a 2065855864 byte allocation with 12582912 free bytes and 508MB until OOM, max allowed footprint 16479016, growth limit 536870912
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
        at com.googlecode.mp4parser.AbstractBox.a(AbstractBox.java:110)
        at com.coremedia.iso.AbstractBoxParser.a(AbstractBoxParser.java:107)
        at com.googlecode.mp4parser.BasicContainer.akY(BasicContainer.java:185)
        at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
        at com.googlecode.mp4parser.util.LazyList.aqe(LazyList.java:30)
        at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
        at com.googlecode.mp4parser.BasicContainer.m(BasicContainer.java:80)
        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
        at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
        at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.a(MovieCreator.java:57)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.lO(MovieCreator.java:38)

**Comment by siosilvar** [comment]
Introduced in 1.1.8, resolved in 1.9.37: https://github.com/sannies/mp4parser/pull/288

**Comment by torindev** [comment]
still got the issue...

**Device:** 
Xiaomi Redmi Note 5 (4 / 64), OS Android Oreo 8.1 

**Context:**
Trying to use trim example - [ShortenExample.java](https://github.com/sannies/mp4parser/blob/master/examples/src/main/java/com/googlecode/mp4parser/ShortenExample.java) 

**lib version:**
`implementation 'com.github.sannies.mp4parser:examples:mp4parser-project-1.9.37'`

**Error:**
```
java.lang.OutOfMemoryError: Failed to allocate a 747345552 byte allocation with 8710584 free bytes and 247MB until OOM, max allowed footprint 17421168, growth limit 268435456
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
        at org.mp4parser.support.AbstractBox.parse(AbstractBox.java:96)
        at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:115)
        at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:57)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:52)
        at org.mp4parser.muxer.container.mp4.MovieCreator.build(MovieCreator.java:54)
        at org.mp4parser.muxer.container.mp4.MovieCreator.build(MovieCreator.java:39)
```

**Comment by HBiSoft** [comment]
@torindev have you resolved this issue?

**Comment by HBiSoft** [comment]
@torindev can you please confirm if 1.9.37 -  #288 fixed this issue?

**Comment by HBiSoft** [comment]
@siosilvar #288 didn't fix it.

**Comment by HBiSoft** [comment]
@torindev can you confirm if the new release fixed this:

    implementation 'org.mp4parser:isoparser:1.9.39'
    implementation 'org.mp4parser:muxer:1.9.39'

**Comment by HBiSoft** [comment]
@siosilvar 1.9.37 didn't fix it.

**Comment by HBiSoft** [comment]
Tested with 1.9.39 and still get the same issue. This issue goes back 3 years, I'm not sure this will ever be fixed.

**Comment by mdmoniskhan** [comment]
Ran into this error on some devices, Is there any solution yet?

java.lang.OutOfMemoryError: 
  at java.nio.HeapByteBuffer.<init> (HeapByteBuffer.java:54)
  at java.nio.HeapByteBuffer.<init> (HeapByteBuffer.java:49)
  at java.nio.ByteBuffer.allocate (ByteBuffer.java:261)
  at com.googlecode.mp4parser.AbstractBox.parse (AbstractBox.java:110)
  at com.coremedia.iso.AbstractBoxParser.parseBox (AbstractBoxParser.java:107)
  at com.googlecode.mp4parser.BasicContainer.next (BasicContainer.java:185)
  at com.googlecode.mp4parser.BasicContainer.hasNext (BasicContainer.java:161)
  at com.googlecode.mp4parser.util.LazyList.blowup (LazyList.java:30)
  at com.googlecode.mp4parser.util.LazyList.size (LazyList.java:77)
  at com.googlecode.mp4parser.BasicContainer.getBoxes (BasicContainer.java:80)
  at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init> (DefaultMp4SampleList.java:36)
  at com.coremedia.iso.boxes.mdat.SampleList.<init> (SampleList.java:33)
  at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init> (Mp4TrackImpl.java:64)
  at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build (MovieCreator.java:57)
  at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build (MovieCreator.java:38)
