### ISSUE TITLE
合并MP4视频 抛异常

### ISSUE THREAD

**Issue by 98d** [sannies/mp4parser#354]
A cast to int has gone wrong. Please contact the mp4parser discussion group (3354339107)
                                                                                          at com.googlecode.mp4parser.util.CastUtils.l2i(CastUtils.java:30)
                                                                                          at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
                                                                                          at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
                                                                                          at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
                                                                                          at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
                                                                                          at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
                                                                                          at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
                                                                                          at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
                                                                                          at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
                                                                                          at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
                                                                                          at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
                                                                                          at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
                                                                                          at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)

**Comment by wangjunyanSV** [comment]
我也遇到了同样的问题，如果解决了 请告诉我一声 谢谢
