### ISSUE TITLE
ShortenExample ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jmgirven** [sannies/mp4parser#36]
Further to my comment on issue #24, I created an example Android application that can reproduce the error on my device. I can't really guarantee it the same is the same issue as #24, so I am adding a separate ticket.

The error I am getting when running the Android app is:

```
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(SourceFile:477)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(SourceFile:340)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(SourceFile:301)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(SourceFile:213)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(SourceFile:115)
```

The code for the app is at https://github.com/jmgirven/mp4parser_test.

The video I test with is GOPR1008.MP4 at https://github.com/jmgirven/mp4parser_test/tree/master/app/src/main/assets.

The main code is in https://github.com/jmgirven/mp4parser_test/blob/master/app/src/main/java/com/example/mp4parser/test/mp4parsertest.

If I use a start time of 5000ms and an end time of 8000ms, for example, the code runs find and edits the video to that length. However, if I change the end time to 10000ms, it fails with the above error. Can you reproduce this error?

The video is actually recorded with a GoPro Hero 4.

Thanks,
Jon.

**Comment by sannies** [comment]
Hi,
I just added a new and less complex example as SimpleShortenExample with
just one start- and endtime. It works well with your file. Could you have a
look if the code also works for you?
Best Regards,
Sebastian

2015-01-06 10:27 GMT-08:00 Jonathan Girven <notifications@github.com>:

**Comment by jmgirven** [comment]
Hi,

Thanks for looking into this. I have replaced my ShortenExample with your SimpleShortenExample in my test Android application. I am still getting a crash:

```
 Caused by: java.lang.IndexOutOfBoundsException
        at java.util.Collections$EmptyList.get(Collections.java:102)
        at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(AppendTrack.java:63)
        at com.example.mp4parser.test.mp4parsertest.SimpleShortenExample.startTrim(SimpleShortenExample.java:81)
        at com.example.mp4parser.test.mp4parsertest.MainActivity$ShortenAsync.doInBackground(MainActivity.java:92)
        at com.example.mp4parser.test.mp4parsertest.MainActivity$ShortenAsync.doInBackground(MainActivity.java:60)
```

from the line:

```
movie.addTrack(new AppendTrack(new CroppedTrack(track, startSample1, endSample1)));
```

I see the SimpleShortenExample differs from my ShortenExample by wrapping the CroppedTrack in an AppendTrack. I am using "GOPR1008.MP4" with ```startTime1=5``` and ```endTime=8```.

Strange that it works for you and not me. Could be an issue with Android?

Thanks,
Jon.

**Comment by jmgirven** [comment]
Hi Sebastian,

I am very keen to resolve this issue in my code and would appreciate your assistance.

I have cloned the mp4parser git onto my machine. I checked out the 1.0.5.4 project tag, to be consistent with the maven version I was using previously. I copied com.coremedia, com.googlecode and com.mp4parser java files into my project so I could edit them. Also resources/isoparser-default.properties.

To my gradle maven dependencies I added:
- org.aspectj:aspectjrt:1.8.2
- commons-io:commons-io:2.4
- commons-codec:commons-codec:1.8

Is there something further I need to do? My test app builds successfully and runs, but the error location has moved, so I assume I have incorrectly included your code. I now have:

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:55)
       at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
       at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:60)
       at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
```

I am still using the same video file, start / end time and SimpleShortenExample.

I was hoping I would be able to log the relevant sections of code and figure out where the failure originates from.

Can you tell me what I might be missing from the mp4parser library? If I were to get back to Collections$EmptyList IndexOutOfBoundsException, do you have any suggestion of what I should be checking for?

Thanks,
Jon.

**Comment by sannies** [comment]
It looks a bit like some MP4 weirdness my parser doesn't get. Can you send
me the file?

2015-02-16 20:02 GMT+02:00 Jonathan Girven <notifications@github.com>:

**Comment by jmgirven** [comment]
The file is hosted here:

https://github.com/jmgirven/mp4parser_test/blob/master/app/src/main/assets/GOPR1008.MP4

Thanks

**Comment by sannies** [comment]
Hi,

now I have read your post again and begin to understand. The mp4parser
postpones the actual parsing of the boxes until the last possible moment.
It uses aspectJ and a so called JoinPoint (see
https://github.com/sannies/mp4parser/blob/master/isoparser/src/main/java/com/googlecode/mp4parser/RequiresParseDetailAspect.java).
So whenever a getter or setter is used it runs into this piece of code
(RequiresParseDetailAspect) and calls parseDetails to extract the box'
field from the underlying ByteBuffer. The Java compiler itself doesn't know
how to apply this piece of code to each getter, this is done in a step
after the actual compilation with the aspectJ compiler
(aspectj-maven-plugin in the pom). When you copy files into your project
you need to do the same: You need to run the aspectJ compiler to apply the
aspects to the byte code.
I hope that helps!

Beste Grüße,
Sebastian

2015-02-16 22:13 GMT+02:00 Jonathan Girven <notifications@github.com>:

**Comment by jmgirven** [comment]
OK, thanks, I'll try to include that compile stage in my project.

You don't find any issue cutting down the file I mention?

**Comment by genorarohit** [comment]
Hello I have been facing an issue with saving the cropped video to a file. I tried debugging and the compiler seems to be compiling every statement. But if i try to play the shortened clip from my sdcard, it says the video is corrupted and i cannot play it.  Kindly Help me with this issue. 
Thanks

Here is my code:

 Movie movie = MovieCreator.build(src.getPath());
        // remove all tracks we will create new tracks from the old
        List<Track> tracks = movie.getTracks();
        movie.setTracks(new LinkedList<Track>());
        double startTime = startMs / 1000;
        double endTime = endMs / 1000;

        for (Track track : tracks) {
            long startSample = -1;
            long endSample = -1;

            long currentSample = 0;
            double currentTime = 0;

            for (int i = 0; i < track.getSampleDurations().length; i++) {
                if (currentTime <= startTime) {
                    // current sample is still before the new starttime
                    startSample = currentSample;
                }
                if (currentTime <= endTime) {
                    // current sample is after the new start time and still before the new endtime
                    endSample = currentSample;
                } else {
                    // current sample is after the end of the cropped video
                    break;
                }
                currentTime += (double) track.getSampleDurations()[i] / (double) track.getTrackMetaData().getTimescale();
                currentSample++;
            }
            movie.addTrack(new CroppedTrack(track, startSample, endSample));
        }

        Container out1 = new DefaultMp4Builder().build(movie);
        MovieHeaderBox mvhd = Path.getPath(out1, "moov/mvhd");
        mvhd.setMatrix(Matrix.ROTATE_180);
        File testfile = CameraHelper.getOutputMediaFile1(mContext);
        FileOutputStream fos = new FileOutputStream(testfile);
        out1.writeContainer(fos.getChannel());
        fos.close();
