### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException: java.lang.OutOfMemoryError: Failed to allocate a 671088628 byte allocation with 33542432 free bytes and 431MB until OOM

### ISSUE THREAD

**Issue by zhuoshirong** [sannies/mp4parser#362]
io.reactivex.exceptions.UndeliverableException: java.lang.OutOfMemoryError: Failed to allocate a 671088628 byte allocation with 33542432 free bytes and 431MB until OOM
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 671088628 byte allocation with 33542432 free bytes and 431MB until OOM
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
        at com.googlecode.mp4parser.AbstractBox.parse(AbstractBox.java:110)
        at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
        at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
        at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
        at com.googlecode.mp4parser.util.LazyList.blowup(LazyList.java:30)
        at com.googlecode.mp4parser.util.LazyList.size(LazyList.java:77)
        at com.googlecode.mp4parser.BasicContainer.getBoxes(BasicContainer.java:80)
        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:36)
        at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
        at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:64)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
        at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
        at com.kmb2b.KmMall.videoEdit.utils.VideoUtil$3.subscribe(VideoUtil.java:187)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:11194)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by Asmeble** [comment]
raise "-Xmx" value to 7G maybe?
