### ISSUE TITLE
ClassNotFoundException: com.googlecode.mp4parser.util.Matrix

### ISSUE THREAD

**Issue by AndroidDog** [sannies/mp4parser#368]
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/mp4parser/util/Matrix;
        at android.alibaba.support.video.compress.Mp4Movie.<init>(Mp4Movie.java:18)
        at android.alibaba.support.video.compress.VideoController.convertVideo(VideoController.java:343)
        at android.alibaba.support.video.compress.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:62)
        at android.alibaba.support.video.compress.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:43)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.taobao.android.task.Coordinator.runWithTiming(Coordinator.java:351) 
        at com.taobao.android.task.Coordinator$StandaloneTask.run(Coordinator.java:598) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.googlecode.mp4parser.util.Matrix" on path: DexPathList[[zip file "/data/app/com.alibaba.intl.android.apps.poseidon-a5MNQF2bGqIfTbjO6kJN0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.alibaba.intl.android.apps.poseidon-a5MNQF2bGqIfTbjO6kJN0Q==/lib/arm, /data/app/com.alibaba.intl.android.apps.poseidon-a5MNQF2bGqIfTbjO6kJN0Q==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by protectedMan** [comment]
同此问题，寻求解决

**Comment by mslinn** [comment]
Perhaps you want `org.mp4parser.support.Matrix`?

**Comment by mingshu555** [comment]
> Perhaps you want `org.mp4parser.support.Matrix`?

have the same error

**Comment by mslinn** [comment]
No idea. This project's code is a mess and the documentation never got written. I removed this dependency from my project and found another way forward. Not listening to comments any longer.

**Comment by HBiSoft** [comment]
There is 2 reasons why this could be happening.

1. You did not implement the library correctly. Make sure you have the following in your `build.gradle` 
```java
implementation 'org.mp4parser:isoparser:1.9.41'
implementation 'org.mp4parser:muxer:1.9.41'
```
2. Your progaurd is removing packages for some reason. Add the following in you `proguard-rules.pro`:

```java
-keep class org.mp4parser:isoparser.** { *; }
-keep class org.mp4parser:muxer.** { *; }
```

**Comment by kdblue** [comment]
Simply You are missing this library.

`implementation 'com.googlecode.mp4parser:isoparser:1.1.22'`

**Comment by charlieaboumoussa** [comment]
I added implementation 'com.googlecode.mp4parser:isoparser:1.1.22'.
It gives this error: Surface frame wait timed out.
Please if someone can help. Thank you!

**Comment by ifjgm005** [comment]
This may be caused by the conflict between the Plugin plug-in written by the Hugo project and the AspectJX plug-in of Hu Jiang.

**Comment by mingshu555** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
