### ISSUE TITLE
Can't load mp3

### ISSUE THREAD

**Issue by NoobyPilot** [sannies/mp4parser#389]
Every time I try to load an mp3, i tried some downloaded and some self recorded, i get the following error:

java.io.IOException: Expected Start Word 0x7ff
	at org.mp4parser.muxer.tracks.MP3TrackImpl.readMP3Header(MP3TrackImpl.java:174)
	at org.mp4parser.muxer.tracks.MP3TrackImpl.readSamples(MP3TrackImpl.java:145)
	at org.mp4parser.muxer.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:53)
	at org.mp4parser.muxer.tracks.MP3TrackImpl.<init>(MP3TrackImpl.java:46)

I couldn't seem to find any Issue describing this problem, so I just want to ask: Is there already a known reason thatcauses this problem and/or a known way how to fix it?

**Comment by HBiSoft** [comment]
Have a look at this question #25

**Comment by 3c133ps3d** [comment]
Solution is simple: don't use MP3 files.
