### ISSUE TITLE
com.googlecode.mp4parser.h264.model.PictureParameterSet.seq_parameter_set_id' on a null object ？？？

### ISSUE THREAD

**Issue by 443030789** [sannies/mp4parser#402]
│ args[0] = h264ToMp4
    │ args[1] = java.lang.NullPointerException: Attempt to read from field 'int com.googlecode.mp4parser.h264.model.PictureParameterSet.seq_parameter_set_id' on a null object reference
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.SliceHeader.<init>(SliceHeader.java:72)
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl$1FirstVclNalDetector.<init>(H264TrackImpl.java:221)
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:293)
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:107)
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:83)
    │ 	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H

**Comment by shaobinyao** [comment]
> │ args[0] = h264ToMp4
> │ args[1] = java.lang.NullPointerException: Attempt to read from field 'int com.googlecode.mp4parser.h264.model.PictureParameterSet.seq_parameter_set_id' on a null object reference
> │ at com.googlecode.mp4parser.authoring.tracks.h264.SliceHeader.(SliceHeader.java:72)
> │ at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl$1FirstVclNalDetector.(H264TrackImpl.java:221)
> │ at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:293)
> │ at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:107)
> │ at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.(H264TrackImpl.java:83)
> │ at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.(H

you have to comfirm the first frame is key frame.
