### ISSUE TITLE
RuntimeException when attempting to mux

### ISSUE THREAD

**Issue by laurencedawson** [sannies/mp4parser#405]
When following the instructions in the README and trying to mux two files I'm getting the following error.

Any ideas?

```
java.lang.RuntimeException: PPS with ids  available but not 2
	at org.mp4parser.muxer.tracks.h264.SliceHeader.<init>(SliceHeader.java:73)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl$1FirstVclNalDetector.<init>(H264TrackImpl.java:242)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:314)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:138)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:98)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:103)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:107)
```

**Comment by milapchokshi-simformsolutions** [comment]
@laurencedawson did you get any solutions for the same? i am getting the same error, if you can help me then it would be so great. thanks
