### ISSUE TITLE
Unknown NAL Errors

### ISSUE THREAD

**Issue by drveresh** [sannies/mp4parser#415]
I am trying to join  an audio(aac) and video(mp4) file, but I am getting below errors:

```
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 19
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 19
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 19
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
May 11, 2020 10:50:51 PM org.mp4parser.muxer.tracks.h264.H264TrackImpl readSamples
WARNING: Unknown NAL unit type: 22
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:682)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:270)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.getNalUnitHeader(H264TrackImpl.java:106)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:300)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:117)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:88)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:93)
	at org.mp4parser.muxer.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:97)
```

Please clarify me and also hope you display meaningful errors unlike these.  Thanks.

**Comment by arighosh2014** [comment]
I am also getting the same issue
