### ISSUE TITLE
ArrayIndexOutOfBoundsException occurs : MovieCreator.build(videoFile)

### ISSUE THREAD

**Issue by chenweitracy** [sannies/mp4parser#54]
Hi,Sannies,
      I try to use this method to create a Movie instance,but exception occurs.
      Look forward to your replying,thx.
code:
        String videoFile = "F:/media/v2.mp4";
        String track1 = "F:/media/m3.aac";
        String track2 = "F:/media/m4.aac";

        Movie m = MovieCreator.build(videoFile);
        
        Track aac1 = new AACTrackImpl(new FileDataSourceImpl(track1));
        Track aac2 = new AACTrackImpl(new FileDataSourceImpl(track2));
        
        m.addTrack(aac1);
        m.addTrack(aac2);
        
        
        DefaultMp4Builder mp4Builder = new DefaultMp4Builder();
        Container out = mp4Builder.build(m);
        FileOutputStream fos = new FileOutputStream("1.mp4");
        FileChannel fc = fos.getChannel();
        out.writeContainer(fc);
        fos.close();

exception:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList.<init>(DefaultMp4SampleList.java:55)
	at com.coremedia.iso.boxes.mdat.SampleList.<init>(SampleList.java:33)
	at com.googlecode.mp4parser.authoring.Mp4TrackImpl.<init>(Mp4TrackImpl.java:60)
	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
	at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
	at com.googlecode.mp4parser.MuxMp4SourcesExample.main(MuxMp4SourcesExample.java:27)

**Comment by chenweitracy** [comment]
S

**Comment by sannies** [comment]
Hi Chen ( or Wei or Tracy ?)
this eror happens (two possible reasons), when:

(1) The MP4 file is erroneous -. this can be quickly checked by playing the
file in one of the many video players available
(2) --> most likely <-- you copied the code into your project and didn't
use the aspectJ compiler.

Grüße,
Sebastian

Am 04.03.2015 09:32 schrieb "chenweitracy" <notifications@github.com>:

**Comment by chenweitracy** [comment]
Thanks.

**Comment by chenweitracy** [comment]
And call me Chen....^_^
