### ISSUE TITLE
How to trim video more than 2GB?

### ISSUE THREAD

**Issue by cairnechen** [sannies/mp4parser#63]
I have saw somthing like "Chunks of more than 2GB are now possible "

but still don't know how to trim video more than 2GB, is there any solution to this problem?

log is here:

    java.lang.IllegalArgumentException: offset=4293713920 size=409
            at java.nio.MemoryBlock.mmap(MemoryBlock.java:107)
            at java.nio.FileChannelImpl.map(FileChannelImpl.java:257)
            at com.googlecode.mp4parser.FileDataSourceImpl.map(FileDataSourceImpl.java:61)
            at com.googlecode.mp4parser.AbstractBox.readContent(AbstractBox.java:68)
            at com.googlecode.mp4parser.AbstractBox.parseDetails(AbstractBox.java:171)
            at com.googlecode.mp4parser.RequiresParseDetailAspect.before(RequiresParseDetailAspect.java:54)
            at com.coremedia.iso.boxes.TrackHeaderBox.getTrackId(TrackHeaderBox.java:69)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:57)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)

**Comment by sannies** [comment]
Are you on Android? At one point it seemed to me that Android cannot do any memory map operation via java when the start offset is bigger than 2^32. 
Try to open the file on Desktop Java, when that fails, then there is a bug in isoparser. If it works on Desktop Java but not on Android then the bug is in Android. I might find a workaround but not sure if possible.

**Comment by grosalex** [comment]
Hello,
Did you find a solution? I've a similar issu : https://github.com/sannies/mp4parser/issues/194
Sorry I haven't saw this issu when I posted mine.

Regards,
