### ISSUE TITLE
 java.lang.SecurityException: Incorrect signature on Nexus 5 - API 21

### ISSUE THREAD

**Issue by renatofernandes28** [sannies/mp4parser#64]
When i call MovieCreator.build(Path);

where Path = "/storage/emulated/0/DCIM/Camera/VID_20150327_213754.mp4"

I'm getting an Incorrect signature issue would you happen to know why ?

Process: fragment, PID: 27200
    java.lang.SecurityException: Incorrect signature
            at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:223)
            at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:294)
            at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:268)
            at java.util.jar.JarFile.getInputStream(JarFile.java:380)
            at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
            at java.net.URL.openStream(URL.java:470)
            at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
            at java.lang.Class.getResourceAsStream(Class.java:1334)
            at com.coremedia.iso.PropertyBoxParserImpl.<init>(PropertyBoxParserImpl.java:39)
            at com.coremedia.iso.IsoFile.<init>(IsoFile.java:59)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:49)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
            at fragment.VideoTrimmingFragment.trimVideo(VideoTrimmingFragment.java:242)
            at fragment.VideoTrimmingFragment.access$100(VideoTrimmingFragment.java:47)
            at fragment.VideoTrimmingFragment$4.onLongClick(VideoTrimmingFragment.java:201)
            at android.view.View.performLongClick(View.java:4795)
            at android.view.View$CheckForLongPress.run(View.java:19723)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by sannies** [comment]
This cause of this error is unclear to me as the jar is not even signed.
You might want to try the same with different jar (include properties file
and access it via a class inside of the jar). Does that work?
Am 28.03.2015 03:40 schrieb "renatofernandes28" <notifications@github.com>:

**Comment by renatofernandes28** [comment]
It looked like it was an android API bug ... thanks for the reply! :)
