### ISSUE TITLE
Tutorial how to set up aspectj runtime weaving with gradle ?

### ISSUE THREAD

**Issue by renatofernandes28** [sannies/mp4parser#65]
I'm currently getting 

 java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class java.lang.String]
            at com.coremedia.iso.PropertyBoxParserImpl.createBox(PropertyBoxParserImpl.java:120)
            at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:101)

Which to me looks like it could be something to do with me not setting up aspect-j

I'm on android.. and I'm not too familiar with the gradle compiler options. Is there like a sample gradle file/ tutorial out there I can use to make sure I have aspectJ runtime weaving compiling ? I've search a lot on the internet with no avail.. Was wondering how the any fellow android developer is doing it ?

Thanks :)

**Comment by sannies** [comment]
I'll help you when you give me a good reason not to use a precompiled release version  ;)

**Comment by renatofernandes28** [comment]
Precompiled version ? Sorry this stuff is a little but new to me.

Is there like a library I can use in the gradle dependencies ? Because i've tried adding dependencies and classpaths ... but still getting the runtime exception. Unless the paths I've added are wrong

Right now i added the following in my dependencies:

 compile('org.aspectj:aspectjrt:1.8.1')

**Comment by renatofernandes28** [comment]
So I think i am using the precompiled release version

I have in gradle depenecy like so

dependencies {
compile('com.googlecode.mp4parser:isoparser:1.0.5.4')
}

but Still getting the 
java.lang.RuntimeException: java.lang.NoSuchMethodException: [class java.lang.String]
at com.coremedia.iso.PropertyBoxParserImpl.createBox(PropertyBoxParserImpl.java:120)

**Comment by sannies** [comment]
Ok. Could you send me the full  stack trace? I  don't see where it is
actually  coming from.
Am 28.03.2015 23:28 schrieb "renatofernandes28" <notifications@github.com>:

**Comment by renatofernandes28** [comment]
@sannies Full Stack
    java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class java.lang.String]
            at com.coremedia.iso.PropertyBoxParserImpl.createBox(PropertyBoxParserImpl.java:120)
            at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:101)
            at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
            at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
            at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:147)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
            at com.googlecode.mp4parser.util.Path.getPaths(Path.java:87)
            at com.googlecode.mp4parser.util.Path.getPath(Path.java:73)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:53)
            at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
            at fragment.VideoTrimmingFragment.trimVideo(VideoTrimmingFragment.java:249)
            at fragment.VideoTrimmingFragment.access$100(VideoTrimmingFragment.java:50)
            at fragment.VideoTrimmingFragment$4.onLongClick(VideoTrimmingFragment.java:208)
            at android.view.View.performLongClick(View.java:4795)
            at android.view.View$CheckForLongPress.run(View.java:19723)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by sannies** [comment]
Hi Renato,

this is still not enough. If you would have a look into the code you see
that this is the stacktrace of the runtimeexception. The root cause is
the NoSuchMethodException
I of course need that stacktrace. Please wrap the failing method call in
your code with try { [failing code] } catch (RuntimeException e) {
e.getCause().printStackTrace() }. This will print the root cause.

Best Regards,
Sebastian

**Comment by renatofernandes28** [comment]
Sorry about that, he is the getCause() StackTrace

It looks like the line
Constructor<Box> constructorObject = clazz.getConstructor(constructorArgsClazz);
in PropertyBoxParserImpl.createBox is throwing the NoSuchMethod Exception



java.lang.NoSuchMethodException: <init> [class java.lang.String]
 at java.lang.Class.getConstructor(Class.java:531)
 at java.lang.Class.getConstructor(Class.java:495)
 at com.coremedia.iso.PropertyBoxParserImpl.createBox(PropertyBoxParserImpl.java:105)
 at com.coremedia.iso.AbstractBoxParser.parseBox(AbstractBoxParser.java:101)
 at com.googlecode.mp4parser.BasicContainer.next(BasicContainer.java:185)
 at com.googlecode.mp4parser.BasicContainer.hasNext(BasicContainer.java:161)
 at com.googlecode.mp4parser.util.LazyList$1.hasNext(LazyList.java:55)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:147)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:95)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:151)
 at com.googlecode.mp4parser.util.Path.getPaths(Path.java:87)
 at com.googlecode.mp4parser.util.Path.getPath(Path.java:73)
 at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:53)
 at com.googlecode.mp4parser.authoring.container.mp4.MovieCreator.build(MovieCreator.java:38)
 at fragment.VideoTrimmingFragment.trimVideo(VideoTrimmingFragment.java:253)
 at fragment.VideoTrimmingFragment.access$100(VideoTrimmingFragment.java:50)

**Comment by aldenml** [comment]
Hi @renatofernandes28 , I think you are getting weird issues with aspectj runtime in android. My recommendation to @sannies is get rid of it but I'm still waiting for discussion in the PR https://github.com/sannies/mp4parser/pull/60 (I'm also getting advantage of this issue to pin you, not that I'm in a hurry).

Best Regards

**Comment by sannies** [comment]
Thank you. We are getting closer. There is a problem in the
isoparser.properties file I would guess. Can you perhaps share the video
with me so that I can find out which one it is (your video is 'using' the
erroneous entry)?
Am 29.03.2015 18:57 schrieb "renatofernandes28" <notifications@github.com>:

**Comment by renatofernandes28** [comment]
@sannies  Sent you the video through email hope it helps with the fixing :)

**Comment by renatofernandes28** [comment]
@sannies It looked like there was a proguarding issue in my app. That most likely messed up the reflection. I got it working now! Thanks for you time !

**Comment by sannies** [comment]
Ohh yes. Proguard and reflection can very tricky.  Thanks for notifying me.

@sannies <https://github.com/sannies> It looked like there was a
proguarding issue in my app. That most likely messed up the reflection. I
got it working now! Thanks for you time !

—
Reply to this email directly or view it on GitHub
<https://github.com/sannies/mp4parser/issues/65#issuecomment-88182817>.

**Comment by elincoln** [comment]
For posterity/sanity, if you've landed here wondering how to resolve the ProGuard issue, here's a scorched-earth approach to fixing your ProGuard config so you can use mp4parser: 
```
-keep class com.coremedia.iso.** { *; }
-keep interface com.coremedia.iso.** { *; }

-keep class com.mp4parser.** { *; }
-keep interface com.mp4parser.** { *; }

-keep class com.googlecode.mp4parser.** { *; }
-keep interface com.googlecode.mp4parser.** { *; }
```
