### ISSUE TITLE
Converting H264 raw stream to Mp4

### ISSUE THREAD

**Issue by mohanraj546** [sannies/mp4parser#80]
I want to convert the raw .h264 stream in to mp4.I am using the mp4 parser
 it is working for some files only and the remaining give the exception as,

STACK_TRACE=java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
 java.util.ArrayList.get(ArrayList.java:310)  com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.createSample(H264TrackImpl.java:39) com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.readSamples(H264TrackImpl.java:372)
com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.parse(H264TrackImpl.java:108)
com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:90)
com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:96) com.googlecode.mp4parser.authoring.tracks.H264TrackImpl.<init>(H264TrackImpl.java:100)

     Please help me how to do this one.

**Comment by sannies** [comment]
As this is something that typically works it must have something todo with
the input.  Could you please make a sample available? (send private if not
suitable for public)
Best regards, Sebastian
Am 29.04.2015 06:52 schrieb "mohanraj546" <notifications@github.com>:

**Comment by mohanraj546** [comment]
okay thank u for reply i will sent ur mail(sample.h264)

**Comment by sannies** [comment]
Broken input file caused Excpetion. https://github.com/sannies/mp4parser/commit/34c5234d28305e3a0871dd9906d06794da936c90 makes it more robust

**Comment by adhirmndl** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.googlecode.mp4parser.authoring.tracks.h264.SliceHeader.<init>(SliceHeader.java:72)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl$1FirstVclNalDetector.<init>(H264TrackImpl.java:221)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.readSamples(H264TrackImpl.java:293)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.parse(H264TrackImpl.java:107)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:83)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:87)
	at com.googlecode.mp4parser.authoring.tracks.h264.H264TrackImpl.<init>(H264TrackImpl.java:91)
	at org.ivis.convert.Parse.main(Parse.java:18)
