### ISSUE TITLE
short mp4 files append error

### ISSUE THREAD

**Issue by PowerCool** [sannies/mp4parser#90]
when short mp4 files append mp4parser occurs exceptions.

source code.
Movie[] inMovies = new Movie[sourceFiles.size()];
        int index = 0;
        for(String sourceFile : sourceFiles){
            log.di("sourceFile : " + sourceFile);
            inMovies[index++] = MovieCreator.build(sourceFile);
        }
        log.di("outputFile : " + outputFile);

        List<Track> videoTracks = new LinkedList<Track>();
        List<Track> audioTracks = new LinkedList<Track>();

        for (Movie m : inMovies) {
            for (Track t : m.getTracks()) {
                if (t.getHandler().equals("soun")) {
                    audioTracks.add(t);
                }
                if (t.getHandler().equals("vide")) {
                    videoTracks.add(t);
                }
            }
        }
        Movie result = new Movie();
        if (audioTracks.size() > 0) {
            result.addTrack(new AppendTrack(audioTracks.toArray(new Track[audioTracks.size()])));
        }
        if (videoTracks.size() > 0) {
            result.addTrack(new AppendTrack(videoTracks.toArray(new Track[videoTracks.size()])));
        }
        Container out = new DefaultMp4Builder().build(result);
        FileChannel fc = new RandomAccessFile(outputFile, "rw").getChannel();
        out.writeContainer(fc);
        fc.close();

        if(deleteAfterMerge == true){
            for(String sourceFile : sourceFiles){
                new File(sourceFile).delete();
            }
        }

exception logs.
06-16 13:55:34.413  31864-31888/? I/TestRunner﹕ java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStco(DefaultMp4Builder.java:497)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createStbl(DefaultMp4Builder.java:360)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createTrackBox(DefaultMp4Builder.java:321)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.createMovieBox(DefaultMp4Builder.java:225)
            at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:115)

**Comment by sannies** [comment]
Could you please send me example files that don't work? Your code is very close to the working example and therefore I guess that the problem is in the files.

**Comment by PowerCool** [comment]
Thanks for reply.

I attached two files(baseSource1.mp4, source1.mp4) to occur exception.

I am wondering why occur exception.

please talk me about reason to occur exception.

2015-06-19 2:39 GMT+09:00 Sebastian Annies <notifications@github.com>:

**Comment by sannies** [comment]
Hi,
I'm very sorry but now that I have some time to look at your files I see that the file attachment have been lost when sending the email to github issues. I guess you'll have to upload them to dropbox or some other service as github issues can't handle file attachments
Best Regards,
Sebastian

**Comment by PowerCool** [comment]
Hi,
My drop box link. 
https://www.dropbox.com/sh/9zdtyygplzn9www/AAAHowv-Yba2sYolIa219_Hea?dl=0

Thank you!

**Comment by sannies** [comment]
Hi,
the rsmedia-test is not correct - well at least a usual video. It only contains a single IDR frame as video and audio. The Decoding Time to Sample Box ("/moov[0]/trak[1]/mdia[0]/minf[0]/stbl[0]/stts[0]") has only a single entry with the delta of zero. That means that this video contains a single frame which displayed for zero timeunits. 
Hmm - is that intended?

Best,
Sebastian

**Comment by PowerCool** [comment]
Hi.
The rsmedia-test is recorded by Mediacodec on android. 

Is this file appending impossible to use the mp4parser?

**Comment by PowerCool** [comment]
Hi,
but these videos are playing well. also these videos was recorded by MediaCodec on android.
What is the problem?

**Comment by sannies** [comment]
The video track shows a track duration of 43881/90000 of a second (~ 0.5
seconds) but contains only a single sample with a duration of zero. The
audio track's duration is 200669/44100 (~ 4.5s).
The sound is AAC with variable duration frames (!?!?!?!?), this is AFAIK
not possible with AAC.

There is something seriously wrong with the file. It's just pure luck that
it's showing anything on certain players.
PotPlayer doesn't play correct sound,  Quicktime doesn't show video,
 Windows Media Player is not playing the file at all, MediaInfo on windows
crashes - just to give you an idea how broken this file is.

You can extract the frame and use it but this is custom work (I'm available
for custom work).

Best Regards,
Sebastian


2015-06-29 2:33 GMT+02:00 PowerCool <notifications@github.com>:
